In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.15.0


In [3]:
hello = tf.constant("Hello")

In [4]:
world = tf.constant(" World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
type(world)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [11]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [12]:
print(result)

b'Hello World'


In [13]:
a = tf.constant(10)

In [14]:
b = tf.constant(20)

In [15]:
type(a)

tensorflow.python.framework.ops.Tensor

In [16]:
type(b)

tensorflow.python.framework.ops.Tensor

In [17]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [18]:
a + b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [19]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [20]:
print(result)

30


In [21]:
const = tf.constant(10)

In [22]:
fill_mat = tf.fill((4,4), 10)

In [24]:
myzeros = tf.zeros((4,4))

In [26]:
ones = tf.ones((4,4))

In [27]:
myrand = tf.random_normal((4,4), mean=0, stddev=1.0)

In [28]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [31]:
my_ops = [const,fill_mat, myzeros, myrand, myrandu]

In [33]:
sess = tf.InteractiveSession()

In [36]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[ 1.4288862  -1.3247337   1.4586463   0.95271164]
 [ 0.07293508  0.6122116  -2.021407    0.08528762]
 [-0.24871215  2.319844    0.92063093 -0.8300045 ]
 [ 1.4473108  -0.4087403  -0.11473714  0.0698825 ]]


[[0.5411929  0.41170144 0.28653967 0.7330303 ]
 [0.72404635 0.52771664 0.98474824 0.47914386]
 [0.4421507  0.20185173 0.08915627 0.61204875]
 [0.37277734 0.19090986 0.9666381  0.71628463]]




In [37]:
a = tf.constant([[1,2],
                [3,4]])

In [38]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [39]:
b = tf.constant([[10],[100]])

In [40]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [41]:
result = tf.matmul(a, b)

In [42]:
sess.run(result)

array([[210],
       [430]], dtype=int32)